version: '3.8'

services:
  kratos-migrate:
    image: oryd/kratos:v0.11.0
    environment:
      - DSN=postgres://craters:kratos@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.11.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
  postgresd:
    image: postgres:15.1
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=craters
      - POSTGRES_PASSWORD=kratos
      - POSTGRES_DB=kratos
    networks:
      - intranet

networks:
  intranet: